/* ============================================================
   File: 3_analysis_queries.sql
   Project: Sales Data Analysis & MIS Dashboard

   Description:
   This script contains analytical SQL queries used to
   evaluate sales performance, product contribution,
   profitability, and inventory risks.

   Tables Used:
   - Sales csv
   - Products csv
   - Stores csv
   - Inventory csv
   ============================================================ */

USE Dataware_house;
GO


/* ============================================================
   1. Total Revenue
   Business Question:
   What is the total revenue generated by all sales?

   Logic:
   Revenue = Quantity × SellingPrice
   Sales table contains quantity, Products table contains price.
   ============================================================ */

SELECT
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Total_Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID;



/* ============================================================
   2. Revenue by Region
   Business Question:
   Which region contributes the most revenue?

   Logic:
   Join Sales with Stores to get region information.
   Aggregate revenue by region.
   ============================================================ */

SELECT 
st.Region,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Stores csv] st
ON s.StoreID = st.StoreID
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
GROUP BY st.Region
ORDER BY Revenue DESC;



/* ============================================================
   3. Top 5 Products by Revenue
   Business Question:
   Which products generate the highest revenue?

   Logic:
   Group sales by product and calculate total revenue.
   Use TOP 5 to identify best-performing products.
   ============================================================ */

SELECT TOP 5
p.ProductName,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY Revenue DESC;



/* ============================================================
   4. Monthly Sales Trend
   Business Question:
   How does revenue change month-to-month?

   Logic:
   Convert Date column to DATE format.
   Extract month and aggregate revenue.
   ============================================================ */

SELECT 
MONTH(CAST(s.Date AS DATE)) AS Sales_Month,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Monthly_Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
GROUP BY 
MONTH(CAST(s.Date AS DATE))
ORDER BY Sales_Month;



/* ============================================================
   5. Yearly Revenue
   Business Question:
   How much revenue was generated each year?

   Logic:
   Extract year from sales date and aggregate revenue.
   ============================================================ */

SELECT 
YEAR(CAST(s.Date AS DATE)) AS Sales_Year,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
GROUP BY YEAR(CAST(s.Date AS DATE));



/* ============================================================
   6. Total Profit
   Business Question:
   What is the total profit generated from all sales?

   Logic:
   Profit = (SellingPrice − CostPrice) × Quantity
   ============================================================ */

SELECT 
SUM(
(CAST(p.SellingPrice AS DECIMAL(10,2)) 
 - CAST(p.CostPrice AS DECIMAL(10,2))) 
 * CAST(s.Quantity AS INT)
) AS Total_Profit
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID;



/* ============================================================
   7. Profit Margin
   Business Question:
   What percentage of revenue is profit?

   Logic:
   Profit Margin = (Total Profit / Total Revenue) × 100
   ============================================================ */

SELECT 
SUM(
    (CAST(p.SellingPrice AS DECIMAL(10,2)) 
     - CAST(p.CostPrice AS DECIMAL(10,2))) 
     * CAST(s.Quantity AS INT)
) * 100.0
/
SUM(
    CAST(s.Quantity AS INT) * 
    CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Profit_Margin_Percentage
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID;



/* ============================================================
   8. Low Stock Alert
   Business Question:
   Which products are below the reorder level?

   Logic:
   Compare CurrentStock with ReorderLevel.
   If CurrentStock < ReorderLevel → reorder required.
   ============================================================ */

SELECT  
p.ProductID,
p.ReorderLevel,
i.StoreID,
i.CurrentStock
FROM [dbo].[Products csv] p
JOIN [dbo].[Inventory csv] i
ON p.ProductID = i.ProductID
WHERE i.CurrentStock < p.ReorderLevel;



/* ============================================================
   9. Top 3 Products Per Region
   Business Question:
   Which products perform best in each region?

   Logic:
   Calculate revenue by product within each region.
   Use RANK() window function to rank products.
   Select top 3 per region.
   ============================================================ */

WITH ProductRevenue AS (
SELECT 
st.Region,
p.ProductName,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Revenue,
RANK() OVER (
PARTITION BY st.Region
ORDER BY 
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) DESC
) AS RankPosition
FROM [dbo].[Sales csv] s
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
JOIN [dbo].[Stores csv] st
ON s.StoreID = st.StoreID
GROUP BY st.Region, p.ProductName
)

SELECT *
FROM ProductRevenue
WHERE RankPosition <= 3;



/* ============================================================
   10. Store Performance
   Business Question:
   Which stores generate the highest revenue?

   Logic:
   Aggregate sales data by store.
   Calculate total units sold and revenue.
   ============================================================ */

SELECT 
st.StoreName,
SUM(CAST(s.Quantity AS INT)) AS Total_Units_Sold,
SUM(
CAST(s.Quantity AS INT) *
CAST(p.SellingPrice AS DECIMAL(10,2))
) AS Revenue
FROM [dbo].[Sales csv] s
JOIN [dbo].[Stores csv] st
ON s.StoreID = st.StoreID
JOIN [dbo].[Products csv] p
ON s.ProductID = p.ProductID
GROUP BY st.StoreName
ORDER BY Revenue DESC;
